# Generated by Django 2.1.3 on 2021-03-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('PustotaA', models.CharField(max_length=50)),
                ('Tel1B', models.CharField(max_length=100)),
                ('Tel2C', models.CharField(max_length=100)),
                ('Typ_zvonkaD', models.CharField(choices=[('cisco-voice-gateway', 'cisco-voice-gateway'), ('inside-users', 'inside-users'), ('longdistance', 'longdistance')], max_length=100)),
                ('KtoE', models.CharField(max_length=100)),
                ('SIPF', models.CharField(max_length=100)),
                ('SIPG', models.CharField(max_length=100)),
                ('StatusH', models.CharField(max_length=100)),
                ('SIPI', models.CharField(max_length=100)),
                ('TimeStartJ', models.DateTimeField(max_length=100, null=True)),
                ('TimeMidK', models.CharField(max_length=100)),
                ('TimeFFL', models.DateTimeField(max_length=100, null=True)),
                ('Number1M', models.CharField(max_length=100)),
                ('Number2N', models.CharField(max_length=100)),
                ('StateO', models.CharField(max_length=100)),
                ('DocP', models.CharField(max_length=100)),
                ('IdQ', models.CharField(max_length=100)),
                ('TimeStartJ2', models.DateField()),
            ],
        ),
    ]
